/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWUpVcnpJMkRQbm1lZ0N3MzJVbVRXdUJxQmhDQmY5VEdNRXphMi9SSFJrST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTGN2SHdtcTFGdGhpZ0czaUpBMnRrTXppaDJZT1E0N2haR2M1YVNvMC9ucz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnR2ZIRCt0S3B3VlZPanNKdGR4NXA3VGNzK0N5WWUwSG9qcVR0OUs1ckZVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJISlo1MlFEWGRxS29kbHAvcXZhWWdhazJYWm05Qm5uNjJVbXJoOUZ2VHpRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFIY1NZdkphNmthb0p1OXQva0VlcWNCK3MrK3JIZXo5NzA2SXNjTHNPR3M9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImhxWVRLMFR3d2xDVVVJVldId24vVGpvMEhZOHdWTmViNUxDa0pZRi9tbTQ9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQUM5ZU9Fb1Q4SGVpcU1kZFdhYlhFRFVoRmx1emJkZURGMUNBQTc3Rk5Gaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaDhZT2w3cWNkcmFTaEdYNXR3T3ZBTHNSNEd2L1duWmdHTElCTE5vMk1XOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjJBL2thcjdvcXNrMWcrcG5vT1g3ZGZlaWgwdTZsWW85RzN5TmNKR0tIOFdyMWl1NVFRVWtWREpLZGtoUHRXdk1VZnhHQXhsOFVPRkVJdTY0UWR2WWdBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTQsImFkdlNlY3JldEtleSI6ImhXVFNoMHJuOVRPeDNXK3NreE1GQ2V5cUNZelMxRUFxQ2l2cDZRMlZaT009IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkUtNTZ6R244UmtHY2FfWF80bHg4eXciLCJwaG9uZUlkIjoiOGU3YjJkNDgtYzQwNS00ODI4LWFkMmEtZGQyOTM1OWQyZjdkIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVZT1RGRlZCeGxlc1FyaTVobU5YcnFGaHJVdz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI1MEsxM0h4Ui9NSExwdW1HMk9uYTlmMEgvUmc9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiM0xXNEw4TE4iLCJtZSI6eyJpZCI6IjIzNzY1NjM2MDMxNzo0M0BzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS0hmK3N3R0VLQys4N2tHR0F3Z0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiK0R1a08wNW5ycjF3NWpFMVg3dzFHUHdHK2MwSGZxWGp1NHNmQ0dWem9UMD0iLCJhY2NvdW50U2lnbmF0dXJlIjoiSkg1NXFkYk10OVdCV0dPYi8zRnhBQUhCaGE0d25HTVdLamJQR0YzRzBzdGNOdjdkTXFDQ242d1FOMGxPY2dZMlR3eU12TFAwb3ExY3FxQ0U3VGxIQ0E9PSIsImRldmljZVNpZ25hdHVyZSI6Ii9OTTFPT2N2Rnp4WG10TE1FUmFVRTVkVDVZRjVFVHdWdklyOUt5MTc1Y3JJSTVoTnFTOVEvOGFLNnV3VEs1Ny9UQklxaXc2OVAxWklvbU43TUgxUWhRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM3NjU2MzYwMzE3OjQzQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmZnN3BEdE9aNjY5Y09ZeE5WKzhOUmo4QnZuTkIzNmw0N3VMSHdobGM2RTkifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzIwNDI1NDEsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQzVHIn0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
